name: Deploy Node app on AWS Elastic Beanstalk

env:
  APP_NAME: gerrard-nodejs-app
  S3_BUCKET: gerrard-nodejs-app-bucket
  AWS_REGION: eu-west-2
  AWS_PLATFORM: Docker
  PIPELINE_ID: ${GITHUB_RUN_ID}-${GITHUB_RUN_NUMBER}

on:
  push:
    branches: [ main ]

jobs:
  create_eb_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials 
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - run: |
          AWS_VERSION_LABEL=${{env.APP_NAME}}-${{env.PIPELINE_ID}}

          echo "Creating Source Bundle"
          zip -r ${{env.APP_NAME}}.zip app.js Dockerfile dockerignore package.json
          S3_KEY="$AWS_VERSION_LABEL.zip"

          echo "Uploading Source Bundle to S3"
          aws s3 cp ${{env.APP_NAME}}.zip s3://${{env.S3_BUCKET}}/${S3_KEY} --region ${{env.AWS_REGION}}

          echo "Creating Elastic Beanstalk version"
          aws elasticbeanstalk create-application-version --application-name ${{env.APP_NAME}} --version-label $AWS_VERSION_LABEL --region ${{env.AWS_REGION}} --source-bundle S3Bucket=${{env.S3_BUCKET}},S3Key=${S3_KEY} --auto-create-application

  deploy_aws:
    needs: [create_eb_version]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6 (needed for eb cli)
        uses: actions/setup-python@v1
        with:
          python-version: "3.6"
      - name: Configure AWS credentials 
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-id: ${{ secrets.AWS_ID }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - run: |
          AWS_VERSION_LABEL=${{env.APP_NAME}}-${{env.PIPELINE_ID}}

          echo "Installing Elastic Beanstalk Cli"
          python -m pip install --upgrade pip
          pip install awsebcli --upgrade
          eb --version
          mkdir ~/.ssh
          touch ~/.ssh/gerrard-eb-key.pem
          echo "-----BEGIN RSA PRIVATE KEY-----
MIIEowIBAAKCAQEAidk2+6+wvwWZQAUEFYCmUIF/bxcIRMLPxgyhEU9aYTaJ8cwe
OmzmYx9YC2yfu6ievoIMNqOL+uz/HW/DEDoMhtn6u9HuFg4vPHw2jbZtQ9vSStrJ
tPTRiwVyt0/ScIYvF5xFA14hscJB5+sHHy3V6h9LrE3+9XpljKFzKphg4+SCWKqZ
J+clEso7aafiF/lTGdb+BaRrglSMSp6phjx2Iy1x4gkfCcPeMtmJeGBqZ1rb+Uaw
Mh26SETgTUn0mHIyteDllcZieZzlfKgNQ8VmaGsCq0kdFasHt5ndiSpomMWX9KM0
76m3G16fmPVPb5rrd8YZPMO3sOQGV/KbwIXvrQIDAQABAoIBAD4RfS1klVvdpHxs
BcO80qYrOPsHTuTPJwjRBPErXtGo4gHq262I/U+ifF1ggqfXq+qx2df8WfoZHmHd
weIbkSpjGf/Z7a8moeRFNbcnbhmA8DZePzZoibVkNZwOp/2cnbWu2nBCwT8t7ckE
TYefdtNdVhB2aheUDgd9ZsLGK9JQlYzW+8tfrRgb0s84b9DUeX5yjG0XArzlaGBA
LOZLetoG1ajQlycrTruSP76risFLLLVkXX+sq1Xg4Vx8f9GYW3TLaI0ai1GhAv76
TfMxbeG0i8qox1oyyeDtoi/Ewv4q0nFG+h5l6bsWGcdFkh1ikM9bRjahI291dAjE
3Spc++0CgYEA2/KmwecE2dr3851F81EhXzT63D8XlhDCy13GjGl+2YKMjEGlHc1p
jFZj5yaOW9eXAo5PdlWwDN+7cY6hpXdV1xpC8yaL7jzGu5tLBZEJ3IndXownSBGE
RPQdp8/OD0c4wLOfwhfAbMf20JL8K7j3YlxTmw1/Wgw8OqZpXpamt0cCgYEAoHGM
baDa3Rqlo1KWbUB8gxSvwj8AzpLWgwech8M3fXhRJ/p5FgzIM8R9YN1ygwvo0s+d
u3zBa47T7OyRhmqUnVtXvBILwErsJDTuHeKkoFrHt9JMb72g5mMN+LlyrC1ZgynJ
N2fRNN8qlo+lwfXXXnFS0HrD6x+wlpKVW+GCg2sCgYB1X1cH8J1RGJ3q3gm/H5Nc
eCxKrkyK42TgG6nhskZkEluoWTug3MYvgsaLSrL7ZeALGCBleLKbHCWuIrw2Tal8
QWJq2S4hM0OmR+fQD6cgjl2Yn9gyiE56cX8F10oSMyKhCvn9HKmuI0Od6GIzfuBd
GAHxo1FLn23gqn9eX6yV7wKBgQCEIr/6kZ1ut0FvLtdAhvmEowbVPToW5wvPwfcC
QJ50sSB1gm0y4bgIGmz/16E1mBtZcy9+d5J8WJbk6zg2sZRPvCiXdW1EIvA0KXtq
FXxrrBgLpiDZbh0TYMTi8Sgl8PtlcIaNIO1FU/4pHYjwIt4Ko94GYPT1sZWnjHWB
xEnOnQKBgHEp5oPtyT1dL7T7m0MC3BPSnh1I24piNB9douQ7OTkOflYg7HAbzrui
o31mKW5juPwoQ8+DEf1/bIsZZnksgb2dPNOYbwNoCVIvNIWALI7E2Ce32i+hqOpY
Pp5ztG0x3S1ab6o8hRPeByMyOy910sGgKBOeFMOH4xqUv69jg5gp
-----END RSA PRIVATE KEY-----" > ~/.ssh/gerrard-eb-key.pem
          chmod 400 ~/.ssh/gerrard-eb-key.pem
          ls -l ~/.ssh/gerrard-eb-key.pem

          echo "Deploy init"

          eb init -i ${{env.APP_NAME}} -p ${{env.AWS_PLATFORM}} -k ${{secrets.AWS_ID}} --region ${{env.AWS_REGION}}
          eb deploy ${{env.APP_NAME}} --version ${AWS_VERSION_LABEL}
          echo "Deploy finished"
